language: go
go:
- '1.14'
stages:
  - test
jobs:
  include:
  - stage: test
    script: 
      - export GO111MODULE=on #enable golang modules
      - go mod vendor
      - go test -race
      - cat go.sum #document for each library the version used